CREATE TABLE IF NOT EXISTS products (
    identifier INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(128) NOT NULL,
    price INTEGER,

    PRIMARY KEY (identifier)
);

CREATE TABLE IF NOT EXISTS users (
    identifier INTEGER GENERATED BY DEFAULT AS IDENTITY,
    login VARCHAR(128) NOT NULL,
    password VARCHAR(128) NOT NULL,
    status BOOLEAN NOT NULL,

    PRIMARY KEY (identifier)
);

-- CREATE TABLE test.products
-- (
--     identifier INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
--     name VARCHAR(30) NOT NULL ,
--     price INTEGER
-- );