DROP SCHEMA IF EXISTS chat CASCADE;
CREATE SCHEMA IF NOT EXISTS chat;

CREATE TABLE IF NOT EXISTS chat.users
(
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    login text UNIQUE NOT NULL,
    password text NOT NULL
);

CREATE TABLE IF NOT EXISTS chat.chatrooms
(
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name text UNIQUE NOT NULL,
    owner INTEGER NOT NULL REFERENCES chat.users(id)
);

CREATE TABLE IF NOT EXISTS chat.messages
(
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    author INTEGER REFERENCES chat.users(id) NOT NULL,
    chatroom INTEGER REFERENCES chat.chatrooms(id) ON DELETE CASCADE,
    text text NOT NULL,
    datetime TIMESTAMP NOT NULL
);

