DROP SCHEMA IF EXISTS orm CASCADE;
CREATE SCHEMA IF NOT EXISTS orm;

CREATE TABLE IF NOT EXISTS orm.users(
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    age INTEGER NOT NULL
)